In [3]:
#https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linprog.html

In [1]:
from scipy.optimize import linprog

# Test

In [4]:
>>> c = [-1, 4]
>>> A = [[-3, 1], [1, 2]]
>>> b = [6, 4]
>>> x0_bounds = (None, None)
>>> x1_bounds = (-3, None)
>>> from scipy.optimize import linprog
>>> res = linprog(c, A_ub=A, b_ub=b, bounds=[x0_bounds, x1_bounds])

In [8]:
res

     con: array([], dtype=float64)
     fun: -22.0
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([3.90000000e+01, 1.77635684e-15])
  status: 0
 success: True
       x: array([10., -3.])

# Promotion Policy optimization

In [20]:
import pandas as pd
import numpy as np

## Transition matrices

In [70]:
#df_prom = pd.read_clipboard(header=None)
#df_prom = np.array([[eval(x.replace(',','.')) for x in lst] for lst in df_prom.values])
#df_prom

In [71]:
#df_noprom = pd.read_clipboard(header=None)
#df_noprom = np.array([[eval(x.replace(',','.')) for x in lst] for lst in df_noprom.values])
#df_noprom

In [76]:
df_prom = \
np.array([[0.42304713, 0.099212809, 0.06149504, 0.416245021],
 [0.345787141, 0.210922391, 0.214818328, 0.22847214],
 [0.214721697, 0.203372485, 0.444736585, 0.137169234],
 [0.148860601, 0.026640066, 0.019077087, 0.805422247]])

In [77]:
df_noprom = \
np.array([[0.41460088, 0.062302519, 0.026682139, 0.496414462],
 [0.383677194, 0.174386755, 0.115838466, 0.326097585],
 [0.274194963, 0.206881578, 0.280890917, 0.238032542],
 [0.106374021, 0.012100243, 0.005322744, 0.876202993]])

In [80]:
c_rev_prom = np.array([6.974400935, 18.091354, 43.75314058, 0])
c_rev_noprom = np.array([14.0327348, 51.71727749, 139.2049217, 0])

In [48]:
alpha = 0.9

In [50]:
d_prom = 2
d_noprom = 0

In [159]:
df_prom.T[0][:]

array([0.42304713, 0.34578714, 0.2147217 , 0.1488606 ])

In [137]:
m = np.matrix(df_prom)
m

matrix([[0.42304713, 0.09921281, 0.06149504, 0.41624502],
        [0.34578714, 0.21092239, 0.21481833, 0.22847214],
        [0.2147217 , 0.20337248, 0.44473659, 0.13716923],
        [0.1488606 , 0.02664007, 0.01907709, 0.80542225]])

In [151]:
np.array(m[:,0])


array([[0.42304713],
       [0.34578714],
       [0.2147217 ],
       [0.1488606 ]])

In [156]:
np.array([alpha*m[:,0].T - um[0], alpha*m[:,1].T - um[1], alpha*m[:,2].T - um[2], alpha*m[:,3].T - um[3]])

array([[[-0.61925758,  0.31120843,  0.19324953,  0.13397454]],

       [[ 0.08929153, -0.81016985,  0.18303524,  0.02397606]],

       [[ 0.05534554,  0.1933365 , -0.59973707,  0.01716938]],

       [[ 0.37462052,  0.20562493,  0.12345231, -0.27511998]]])

## Linear programming

In [165]:
def lp_solve(P, c_rev, d_cost, alpha):
    c = [1,1,1,1]
    um = np.eye(4)
    A = [alpha*P[0][:] - um[0], alpha*P[1][:] - um[1], alpha*P[2][:] - um[2], alpha*P[3][:] - um[3]]
    b = d_cost - c_rev
    x0_bounds = x1_bounds = x2_bounds = x3_bounds = (0, None)
    res = linprog(c, A_ub=A, b_ub=b, bounds=[x0_bounds, x1_bounds,x2_bounds,x3_bounds])
    print(res.fun)
    print(res.x, sum(res.x))
    return res

### Results with promotion

In [166]:
res = lp_solve(df_prom, c_rev_prom, 5, 0.9)

142.00840690529137
[16.70930327 42.36776361 82.93134003  0.        ] 142.00840690529137


In [167]:
res = lp_solve(df_prom, c_rev_prom, 4, 0.9)

174.98136408857312
[24.99530965 50.78523039 91.43597985  7.7648442 ] 174.98136408857312


In [168]:
res = lp_solve(df_prom, c_rev_prom, 2, 0.9)

254.981364562187
[ 44.99530976  70.78523049 111.43597997  27.76484434] 254.981364562187


In [169]:
res = lp_solve(df_prom, c_rev_prom, 2, 0.95)

424.1632569530994
[ 86.33462034 113.85324657 156.18216053  67.79322952] 424.16325695309934


In [170]:
res = lp_solve(df_prom, c_rev_prom, 1, 0.95)

504.16325798313903
[106.33462058 133.85324682 176.18216079  87.79322979] 504.16325798313903


In [171]:
res = lp_solve(df_prom, c_rev_prom, 0, 0.95)

584.1632590131794
[126.33462083 153.85324706 196.18216105 107.79323007] 584.1632590131793


In [172]:
res = lp_solve(df_prom, c_rev_prom, 0, 0.988)

2131.4436207071476
[512.35283956 541.32980318 585.06627886 492.6946991 ] 2131.443620707148


### Results without promotion

In [173]:
res = lp_solve(df_noprom, c_rev_noprom, 0, 0.9)

539.6137418899511
[ 81.19522473 144.66799876 263.55882336  50.19169504] 539.6137418899511


In [174]:
res = lp_solve(df_noprom, c_rev_noprom, 0, 0.95)

797.283693105075
[144.15664347 210.05736291 331.73837775 111.33130898] 797.283693105075


In [175]:
res = lp_solve(df_noprom, c_rev_noprom, 0, 0.988)

2368.909458295481
[535.89026625 603.76266473 727.69390088 501.56262644] 2368.909458295481


In [176]:
res = lp_solve(df_noprom, c_rev_noprom, 2, 0.9)

459.6137413980428
[ 61.19522462 124.66799864 243.55882325  30.19169489] 459.6137413980428
